/* ============================================================
   SCENARIO: AIRLINE RESERVATION SYSTEM
   Tables: Airlines -> Flights -> Bookings
   Focus: JOINS integrated with GROUP BY and HAVING
   ============================================================ */


/* ------------------------------------------------------------
   TABLE 1: Airlines (Parent table)
   ------------------------------------------------------------ */
create database Airlines;
use Airlines;
CREATE TABLE Airlines (
    airline_id INT PRIMARY KEY,
    airline_name VARCHAR(50) NOT NULL UNIQUE,
    country VARCHAR(50) DEFAULT 'India',
    established_year INT CHECK (established_year >= 1950)
);

INSERT INTO Airlines VALUES
(1, 'SkyIndia Airlines', 'India', 1995),
(2, 'BlueJet Airways', 'India', 2003),
(3, 'CloudNine Air', 'India', 2010),
(4, 'Falcon Wings', 'India', 1988),
(5, 'AeroSwift', 'India', 2015);


/* ------------------------------------------------------------
   TABLE 2: Flights (Child of Airlines)
   ------------------------------------------------------------ */

CREATE TABLE Flights (
    flight_id INT PRIMARY KEY,
    flight_number VARCHAR(10) UNIQUE NOT NULL,
    airline_id INT,
    origin VARCHAR(50) NOT NULL,
    destination VARCHAR(50) NOT NULL,
    distance_km INT CHECK (distance_km > 0),
    FOREIGN KEY (airline_id) REFERENCES Airlines(airline_id)
);

INSERT INTO Flights VALUES
(101, 'SK101', 1, 'Delhi', 'Mumbai', 1150),
(102, 'SK102', 1, 'Mumbai', 'Bangalore', 840),
(103, 'BJ201', 2, 'Delhi', 'Chennai', 1760),
(104, 'BJ202', 2, 'Chennai', 'Kolkata', 1370),
(105, 'CN301', 3, 'Bangalore', 'Pune', 730),
(106, 'CN302', 3, 'Pune', 'Delhi', 1180),
(107, 'FW401', 4, 'Mumbai', 'Kolkata', 1660),
(108, 'FW402', 4, 'Kolkata', 'Hyderabad', 1180),
(109, 'AS501', 5, 'Hyderabad', 'Delhi', 1260),
(110, 'AS502', 5, 'Delhi', 'Bangalore', 1740);


/* ------------------------------------------------------------
   TABLE 3: Bookings (Child of Flights)
   ------------------------------------------------------------ */

CREATE TABLE Bookings (
    booking_id INT PRIMARY KEY,
    flight_id INT,
    passenger_name VARCHAR(50) NOT NULL,
    seat_class VARCHAR(20) DEFAULT 'Economy',
    fare DECIMAL(10,2) CHECK (fare > 0),
    booking_date DATE,
    FOREIGN KEY (flight_id) REFERENCES Flights(flight_id)
);

INSERT INTO Bookings VALUES
(1, 101, 'Ravi Kumar', 'Economy', 4500.00, '2026-06-01'),
(2, 101, 'Priya Sharma', 'Business', 12000.00, '2026-06-01'),
(3, 102, 'Aman Gupta', 'Economy', 3200.00, '2026-06-02'),
(4, 103, 'Sneha Iyer', 'Economy', 6800.00, '2026-06-02'),
(5, 103, 'Karan Mehta', 'Economy', 6800.00, '2026-06-03'),
(6, 104, 'Divya Nair', 'Business', 15500.00, '2026-06-03'),
(7, 105, 'Rohit Verma', 'Economy', 2900.00, '2026-06-04'),
(8, 106, 'Anjali Singh', 'Economy', 4700.00, '2026-06-04'),
(9, 106, 'Vikram Rao', 'Business', 11200.00, '2026-06-05'),
(10, 107, 'Neha Joshi', 'Economy', 7100.00, '2026-06-05'),
(11, 108, 'Arjun Nair', 'Economy', 4900.00, '2026-06-06'),
(12, 109, 'Meera Pillai', 'Business', 13400.00, '2026-06-06'),
(13, 109, 'Suresh Rao', 'Economy', 5200.00, '2026-06-07'),
(14, 110, 'Kavya Reddy', 'Economy', 7300.00, '2026-06-07'),
(15, 102, 'Ramesh Babu', 'Economy', 3100.00, '2026-06-08'),
(16, 107, 'Pooja Menon', 'Business', 16000.00, '2026-06-08');

-- Note: Flight 104 (BJ202) and Flight 105 (CN301) each have exactly
-- one booking, useful for HAVING COUNT comparisons.


/* ============================================================
   15 QUESTIONS
   ============================================================ */

-- Q1. List every flight along with the name of the airline operating it.
 select 
    f.flight_id,
    f.flight_number,
    a.airline_name,
    f.origin,
    f.destination
from Flights f
inner join Airlines a
on f.airline_id = a.airline_id;


-- Q2. Find the total number of bookings for each flight.
select f.flight_id,f.flight_number,
count(b.booking_id) as Total_booking
from Flights f
inner join Bookings b
on f.flight_id = b.flight_id
group by f.flight_id,f.flight_number;

-- Q3. Find flights that have more than 1 booking.
select f.flight_id,f.flight_number,
count(b.booking_id) as Total_booking
from Flights f
inner join Bookings b
on f.flight_id = b.flight_id
group by f.flight_id,f.flight_number
having count(b.booking_id)>1;

-- Q4. Find the total revenue (sum of fare) generated by each flight.
select f.flight_id,f.flight_number,
sum(b.fare) as Total_revenue
from Flights f 
inner join Bookings b
on f.flight_id=b.flight_id
group by f.flight_id,f.flight_number;


-- Q5. Find flights whose total revenue is more than 10000.
select f.flight_id,f.flight_number,
sum(b.fare) as Total_revenue
from Flights f
inner join Bookings b
on f.flight_id = b.flight_id
group by f.flight_id,f.flight_number
having sum(b.fare) >10000;

-- Q6. Find the total revenue generated by each airline (joining all three tables).
select a.airline_id,a.airline_name,
sum(b.fare) as Total_revenue
from Airlines a
inner join Flights f
on a.airline_id=f.airline_id
inner join Bookings b
on f.flight_id=b.flight_id
group by a.airline_id,a.airline_name;

-- Q7. Find airlines whose total revenue is more than 15000.
select a.airline_id,a.airline_name,
sum(b.fare) as Total_revenue
from Airlines a
inner join Flights f
on a.airline_id=f.airline_id
inner join Bookings b
on f.flight_id=b.flight_id
group by a.airline_id,a.airline_name
having sum(b.fare)>15000;
-- Q8. Find the average fare paid per booking for each airline.
select a.airline_id,a.airline_name,
round(avg(b.fare),0) as Average_fare
from Airlines a
inner join Flights f
on a.airline_id=f.airline_id
inner join Bookings b
on f.flight_id=b.flight_id
group by a.airline_id,a.airline_name;

-- Q9. Find airlines where the average fare is greater than 6000.
select a.airline_id,a.airline_name,
round(avg(b.fare),0) as Average_fare
from Airlines a
inner join Flights f
on a.airline_id=f.airline_id
inner join Bookings b
on f.flight_id=b.flight_id
group by a.airline_id,a.airline_name
having round(avg(b.fare),0)>6000;

-- Q10. Find the number of bookings made in each seat class (Economy vs Business).
select seat_class,
count(seat_class) as Total_bookings
from Bookings
group by seat_class;
-- Q11. Find the total number of flights operated by each airline.
select a.airline_id,a.airline_name,
count(f.flight_id) as Total_flights
from Airlines a
inner join Flights f
on a.airline_id=f.airline_id
inner join Bookings b
on f.Flight_id=b.flight_id
group by a.airline_id,a.airline_name;
-- Q12. Find airlines that operate more than 1 flight.
select a.airline_id,a.airline_name,
count(f.flight_id) as total_flights
from Airlines a
join Flights f
on a.airline_id = f.airline_id
group by a.airline_id, a.airline_name
having COUNT(f.flight_id) > 1;

-- Q13. Find the highest fare paid for each flight.
select f.flight_id,f.flight_number,
max(b.fare) as highest_fare
from Flights f
join Bookings b
on f.flight_id = b.flight_id
group by f.flight_id, f.flight_number;


-- Q14. Find flights where the highest fare paid is 10000 or more.
select f.flight_id,f.flight_number,
max(b.fare) as highest_fare
from Flights f
join Bookings b
on f.flight_id = b.flight_id
group by f.flight_id, f.flight_number
having MAX(b.fare) >= 10000;

-- Q15. Find each airline's average distance covered by its flights, showing
-- only airlines whose average flight distance is more than 1200 km.
select a.airline_id,a.airline_name,
round(avg(f.distance_km),0) AS average_distance
from Airlines a
join Flights f
on a.airline_id = f.airline_id
group by a.airline_id, a.airline_name
having round(avg(f.distance_km),0) > 1200;

-- Q31. Using a CTE, find each sailor's name, ship name,
-- and total distance covered.
WITH SailorDistance AS (
    SELECT sailor_id, SUM(distance_covered_nm) AS total_distance
    FROM VoyageLogs
    GROUP BY sailor_id
)
SELECT s.sailor_name,
       sh.ship_name,
       sd.total_distance
FROM Sailors s
JOIN Ships sh
    ON s.ship_id = sh.ship_id
JOIN SailorDistance sd
    ON s.sailor_id = sd.sailor_id;


-- Q32. Using a CTE, find each ship's name along with
-- the total cargo handled by all its sailors combined.
WITH ShipCargo AS (
    SELECT s.ship_id,
           SUM(v.cargo_handled_tons) AS total_cargo
    FROM Sailors s
    JOIN VoyageLogs v
        ON s.sailor_id = v.sailor_id
    GROUP BY s.ship_id
)
SELECT sh.ship_name,
       sc.total_cargo
FROM Ships sh
JOIN ShipCargo sc
    ON sh.ship_id = sc.ship_id;


-- Q33. Using a CTE, find each sailor's name, rank,
-- total hours on duty, joined with their ship name.
WITH SailorHours AS (
    SELECT sailor_id,
           SUM(hours_on_duty) AS total_hours
    FROM VoyageLogs
    GROUP BY sailor_id
)
SELECT s.sailor_name,
       s.rank_name,
       sh.ship_name,
       h.total_hours
FROM Sailors s
JOIN Ships sh
    ON s.ship_id = sh.ship_id
JOIN SailorHours h
    ON s.sailor_id = h.sailor_id;


-- Q34. Using a CTE, find ships whose combined total distance
-- covered by all sailors is greater than 2000 nautical miles.
WITH ShipDistance AS (
    SELECT s.ship_id,
           SUM(v.distance_covered_nm) AS total_distance
    FROM Sailors s
    JOIN VoyageLogs v
        ON s.sailor_id = v.sailor_id
    GROUP BY s.ship_id
)
SELECT sh.ship_name,
       sd.total_distance
FROM Ships sh
JOIN ShipDistance sd
    ON sh.ship_id = sd.ship_id
WHERE sd.total_distance > 2000;


-- Q35. Using a CTE, find each sailor's name and average hours on duty,
-- along with the ship type they work on.
WITH AvgHours AS (
    SELECT sailor_id,
           AVG(hours_on_duty) AS avg_hours
    FROM VoyageLogs
    GROUP BY sailor_id
)
SELECT s.sailor_name,
       ah.avg_hours,
       sh.ship_type
FROM Sailors s
JOIN Ships sh
    ON s.ship_id = sh.ship_id
JOIN AvgHours ah
    ON s.sailor_id = ah.sailor_id;


-- Q36. Using a CTE, find each ship's name and the number of voyage
-- logs recorded by sailors on that ship.
WITH ShipLogs AS (
    SELECT s.ship_id,
           COUNT(v.log_id) AS total_logs
    FROM Sailors s
    JOIN VoyageLogs v
        ON s.sailor_id = v.sailor_id
    GROUP BY s.ship_id
)
SELECT sh.ship_name,
       sl.total_logs
FROM Ships sh
JOIN ShipLogs sl
    ON sh.ship_id = sl.ship_id;


-- Q37. Using a CTE, find sailors whose total distance covered
-- is above the average total distance across all sailors.
WITH SailorDistance AS (
    SELECT sailor_id,
           SUM(distance_covered_nm) AS total_distance
    FROM VoyageLogs
    GROUP BY sailor_id
),
AverageDistance AS (
    SELECT AVG(total_distance) AS avg_total_distance
    FROM SailorDistance
)
SELECT s.sailor_name,
       sh.ship_name,
       sd.total_distance
FROM Sailors s
JOIN Ships sh
    ON s.ship_id = sh.ship_id
JOIN SailorDistance sd
    ON s.sailor_id = sd.sailor_id
CROSS JOIN AverageDistance ad
WHERE sd.total_distance > ad.avg_total_distance;


-- Q38. Using a CTE, find each rank along with the total cargo
-- handled by sailors of that rank.
WITH RankCargo AS (
    SELECT s.rank_name,
           SUM(v.cargo_handled_tons) AS total_cargo
    FROM Sailors s
    JOIN VoyageLogs v
        ON s.sailor_id = v.sailor_id
    GROUP BY s.rank_name
)
SELECT *
FROM RankCargo;


-- Q39. Using a CTE, find each ship's name and its youngest sailor's age.
WITH YoungestSailor AS (
    SELECT ship_id,
           MIN(age) AS youngest_age
    FROM Sailors
    GROUP BY ship_id
)
SELECT sh.ship_name,
       ys.youngest_age
FROM Ships sh
JOIN YoungestSailor ys
    ON sh.ship_id = ys.ship_id;


-- Q40. Using a CTE, find each sailor's name, ship name,
-- and total contribution (distance + cargo).
WITH SailorContribution AS (
    SELECT sailor_id,
           SUM(distance_covered_nm + cargo_handled_tons)
               AS total_contribution
    FROM VoyageLogs
    GROUP BY sailor_id
)
SELECT s.sailor_name,
       sh.ship_name,
       sc.total_contribution
FROM Sailors s
JOIN Ships sh
    ON s.ship_id = sh.ship_id
JOIN SailorContribution sc
    ON s.sailor_id = sc.sailor_id;